
[tool.poetry]
name = "stashie"
version = "0.0.1"
description = "An asynchronous command line interface to bitbucket server."
authors = ["symonk <jackofspaces@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.19.0"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
ipython = "^7.27.0"
pre-commit = "^2.14.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
